Read the following data set:
https://archive.ics.uci.edu/ml/machine-learning-databases/adult/
Rename the columns as per the description from this file:
https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
Task:
Create a sql db from adult dataset and name it sqladb

1. Select 10 records from the adult sqladb

In [6]:
import pandas as pd
import sqlite3

cols=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race',
               'sex','capital-gain','capital-loss','hours-per-week','native-country','label']

df=pd.read_csv('adult.data.txt', names=cols)
con = sqlite3.connect("sqladb.db")
df.to_sql(name='sqladb', con=con, index=False, if_exists='append')

con.execute("select *from sqladb limit 10").fetchall()

[(39,
  ' State-gov',
  77516,
  ' Bachelors',
  13,
  ' Never-married',
  ' Adm-clerical',
  ' Not-in-family',
  ' White',
  ' Male',
  2174,
  0,
  40,
  ' United-States',
  ' <=50K'),
 (50,
  ' Self-emp-not-inc',
  83311,
  ' Bachelors',
  13,
  ' Married-civ-spouse',
  ' Exec-managerial',
  ' Husband',
  ' White',
  ' Male',
  0,
  0,
  13,
  ' United-States',
  ' <=50K'),
 (38,
  ' Private',
  215646,
  ' HS-grad',
  9,
  ' Divorced',
  ' Handlers-cleaners',
  ' Not-in-family',
  ' White',
  ' Male',
  0,
  0,
  40,
  ' United-States',
  ' <=50K'),
 (53,
  ' Private',
  234721,
  ' 11th',
  7,
  ' Married-civ-spouse',
  ' Handlers-cleaners',
  ' Husband',
  ' Black',
  ' Male',
  0,
  0,
  40,
  ' United-States',
  ' <=50K'),
 (28,
  ' Private',
  338409,
  ' Bachelors',
  13,
  ' Married-civ-spouse',
  ' Prof-specialty',
  ' Wife',
  ' Black',
  ' Female',
  0,
  0,
  40,
  ' Cuba',
  ' <=50K'),
 (37,
  ' Private',
  284582,
  ' Masters',
  14,
  ' Married-civ-spouse',
  ' Exec-managerial',
  ' Wife',
  ' White',
  ' Female',
  0,
  0,
  40,
  ' United-States',
  ' <=50K'),
 (49,
  ' Private',
  160187,
  ' 9th',
  5,
  ' Married-spouse-absent',
  ' Other-service',
  ' Not-in-family',
  ' Black',
  ' Female',
  0,
  0,
  16,
  ' Jamaica',
  ' <=50K'),
 (52,
  ' Self-emp-not-inc',
  209642,
  ' HS-grad',
  9,
  ' Married-civ-spouse',
  ' Exec-managerial',
  ' Husband',
  ' White',
  ' Male',
  0,
  0,
  45,
  ' United-States',
  ' >50K'),
 (31,
  ' Private',
  45781,
  ' Masters',
  14,
  ' Never-married',
  ' Prof-specialty',
  ' Not-in-family',
  ' White',
  ' Female',
  14084,
  0,
  50,
  ' United-States',
  ' >50K'),
 (42,
  ' Private',
  159449,
  ' Bachelors',
  13,
  ' Married-civ-spouse',
  ' Exec-managerial',
  ' Husband',
  ' White',
  ' Male',
  5178,
  0,
  40,
  ' United-States',
  ' >50K')]

2. Show me the average hours per week of all men who are working in private sector

In [13]:
str='''select avg("hours-per-week") from sqladb where trim(sex)="Male" and trim(workclass)="Private"'''
con.execute(str).fetchall()

[(42.22122591006424,)]

3. Show me the frequency table for education, occupation and relationship, separately3.

In [21]:
#education

str='''select education, count(*) from sqladb group by education order by 1 '''
for rec in con.execute(str):
    print(rec)
print('-'*25)

#occupation

str='''select occupation, count(*) from sqladb group by occupation order by 1 '''
for rec in con.execute(str):
    print(rec)
print('-'*25)

#relationship

str='''select relationship, count(*) from sqladb group by relationship order by 1 '''
for rec in con.execute(str):
    print(rec)
print('-'*25)

(' 10th', 1866)
(' 11th', 2350)
(' 12th', 866)
(' 1st-4th', 336)
(' 5th-6th', 666)
(' 7th-8th', 1292)
(' 9th', 1028)
(' Assoc-acdm', 2134)
(' Assoc-voc', 2764)
(' Bachelors', 10710)
(' Doctorate', 826)
(' HS-grad', 21002)
(' Masters', 3446)
(' Preschool', 102)
(' Prof-school', 1152)
(' Some-college', 14582)
-------------------------
(' ?', 3686)
(' Adm-clerical', 7540)
(' Armed-Forces', 18)
(' Craft-repair', 8198)
(' Exec-managerial', 8132)
(' Farming-fishing', 1988)
(' Handlers-cleaners', 2740)
(' Machine-op-inspct', 4004)
(' Other-service', 6590)
(' Priv-house-serv', 298)
(' Prof-specialty', 8280)
(' Protective-serv', 1298)
(' Sales', 7300)
(' Tech-support', 1856)
(' Transport-moving', 3194)
-------------------------
(' Husband', 26386)
(' Not-in-family', 16610)
(' Other-relative', 1962)
(' Own-child', 10136)
(' Unmarried', 6892)
(' Wife', 3136)
-------------------------

4. Are there any people who are married, working in private sector and having a masters
degree

In [26]:
str='''select * from sqladb where trim("marital-status") like ("Married%") and trim(workclass)="Private" and trim(education)="Masters"'''
for rec in con.execute(str):
    print(rec)

(37, ' Private', 284582, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(33, ' Private', 202051, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(76, ' Private', 124191, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(31, ' Private', 99928, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 50, ' United-States', ' <=50K')
(35, ' Private', 138992, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Other-relative', ' White', ' Male', 7298, 0, 40, ' United-States', ' >50K')
(34, ' Private', 142897, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 7298, 0, 35, ' Taiwan', ' >50K')
(62, ' Private', 270092, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(41, ' Private', 445382, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 65, ' United-States', ' >50K')
(33, ' Private', 208405, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(49, ' Private', 192776, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 45, ' United-States', ' >50K')
(51, ' Private', 410114, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(31, ' Private', 118710, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1902, 40, ' United-States', ' >50K')
(34, ' Private', 73585, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' ?', ' <=50K')
(40, ' Private', 170108, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(43, ' Private', 158926, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 0, 50, ' South', ' <=50K')
(51, ' Private', 138022, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(43, ' Private', 227065, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 43, ' United-States', ' >50K')
(38, ' Private', 173208, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(33, ' Private', 354573, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 44, ' United-States', ' >50K')
(25, ' Private', 404616, ' Masters', 14, ' Married-civ-spouse', ' Farming-fishing', ' Not-in-family', ' White', ' Male', 0, 0, 99, ' United-States', ' >50K')
(59, ' Private', 151616, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' <=50K')
(38, ' Private', 22245, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 72, ' ?', ' >50K')
(46, ' Private', 279661, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Black', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(57, ' Private', 89392, ' Masters', 14, ' Married-spouse-absent', ' Prof-specialty', ' Not-in-family', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(65, ' Private', 198766, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 20051, 0, 40, ' United-States', ' >50K')
(55, ' Private', 98361, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 50, ' ?', ' >50K')
(45, ' Private', 46406, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 36, ' England', ' >50K')
(48, ' Private', 126754, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 40, ' United-States', ' >50K')
(54, ' Private', 177927, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(43, ' Private', 201723, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 40, ' United-States', ' >50K')
(41, ' Private', 233955, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 45, ' China', ' >50K')
(49, ' Private', 186078, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 50, ' United-States', ' >50K')
(39, ' Private', 79331, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 15024, 0, 40, ' United-States', ' >50K')
(58, ' Private', 312131, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(34, ' Private', 192002, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(38, ' Private', 119741, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' Black', ' Male', 0, 0, 40, ' United-States', ' >50K')
(37, ' Private', 329980, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 2415, 60, ' United-States', ' >50K')
(40, ' Private', 102606, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(50, ' Private', 147629, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 45, ' United-States', ' >50K')
(39, ' Private', 505119, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' Cuba', ' >50K')
(37, ' Private', 49115, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(44, ' Private', 146659, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1887, 35, ' United-States', ' >50K')
(45, ' Private', 142287, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(29, ' Private', 241431, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 7298, 0, 40, ' United-States', ' >50K')
(41, ' Private', 116379, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 55, ' Taiwan', ' >50K')
(36, ' Private', 116358, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' Taiwan', ' >50K')
(44, ' Private', 198282, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 40, ' United-States', ' >50K')
(43, ' Private', 96102, ' Masters', 14, ' Married-spouse-absent', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(36, ' Private', 107302, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(47, ' Private', 102308, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(26, ' Private', 198163, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(44, ' Private', 178385, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 48, ' India', ' <=50K')
(61, ' Private', 208919, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(38, ' Private', 266645, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(55, ' Private', 153484, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 50, ' United-States', ' >50K')
(32, ' Private', 295589, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(38, ' Private', 242720, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 35, ' United-States', ' >50K')
(54, ' Private', 457237, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(39, ' Private', 96452, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(41, ' Private', 113823, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' England', ' <=50K')
(26, ' Private', 139098, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 5013, 0, 40, ' United-States', ' <=50K')
(36, ' Private', 165799, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(56, ' Private', 192869, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 1977, 44, ' United-States', ' >50K')
(36, ' Private', 120760, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' China', ' <=50K')
(43, ' Private', 102025, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Other', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(38, ' Private', 234901, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 60, ' United-States', ' >50K')
(56, ' Private', 318450, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 80, ' United-States', ' >50K')
(40, ' Private', 71738, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 46, ' United-States', ' >50K')
(53, ' Private', 201127, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 48, ' United-States', ' >50K')
(49, ' Private', 101825, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1977, 40, ' United-States', ' >50K')
(46, ' Private', 324655, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1902, 40, ' ?', ' >50K')
(53, ' Private', 114758, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 65, ' United-States', ' >50K')
(42, ' Private', 201785, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(43, ' Private', 304175, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(49, ' Private', 185041, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(53, ' Private', 424079, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 55, ' United-States', ' >50K')
(34, ' Private', 299635, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' United-States', ' >50K')
(42, ' Private', 107762, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(49, ' Private', 65087, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(37, ' Private', 117381, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(46, ' Private', 55720, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(55, ' Private', 31905, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(32, ' Private', 473133, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 225544, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 40, ' Poland', ' <=50K')
(46, ' Private', 265275, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(47, ' Private', 190139, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(44, ' Private', 116632, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(33, ' Private', 176992, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(44, ' Private', 296728, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(44, ' Private', 112517, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 20, ' United-States', ' >50K')
(29, ' Private', 168479, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(51, ' Private', 146574, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(37, ' Private', 126569, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(35, ' Private', 112271, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')

(49, ' Private', 178749, ' Masters', 14, ' Married-spouse-absent', ' Adm-clerical', ' Unmarried', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(53, ' Private', 106176, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 7298, 0, 60, ' United-States', ' >50K')
(46, ' Private', 137354, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' Philippines', ' >50K')
(35, ' Private', 241126, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 99357, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 15024, 0, 50, ' United-States', ' >50K')
(41, ' Private', 93793, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' >50K')
(50, ' Private', 196193, ' Masters', 14, ' Married-spouse-absent', ' Prof-specialty', ' Other-relative', ' White', ' Male', 0, 0, 60, ' ?', ' <=50K')
(66, ' Private', 216856, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(36, ' Private', 261382, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 15024, 0, 45, ' United-States', ' >50K')
(51, ' Private', 44000, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 99999, 0, 50, ' United-States', ' >50K')
(39, ' Private', 91711, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(40, ' Private', 146520, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(67, ' Private', 195161, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 20051, 0, 60, ' United-States', ' >50K')
(43, ' Private', 102180, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 126675, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(64, ' Private', 149044, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 2057, 60, ' China', ' <=50K')
(41, ' Private', 280167, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 70, ' United-States', ' >50K')
(55, ' Private', 163083, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(34, ' Private', 204470, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(39, ' Private', 194404, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 40, ' United-States', ' >50K')
(33, ' Private', 111567, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 45, ' Germany', ' >50K')
(38, ' Private', 314310, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(37, ' Private', 259785, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(45, ' Private', 127111, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(57, ' Private', 375868, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(44, ' Private', 104196, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(28, ' Private', 209205, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(30, ' Private', 110643, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 4386, 0, 40, ' United-States', ' >50K')
(41, ' Private', 174395, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(42, ' Private', 383493, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(38, ' Private', 241153, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 48, ' United-States', ' >50K')
(43, ' Private', 208277, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 45, ' United-States', ' >50K')
(44, ' Private', 115323, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(43, ' Private', 188808, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(44, ' Private', 125461, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 35, ' United-States', ' >50K')
(57, ' Private', 245193, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(51, ' Private', 182314, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 107302, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' India', ' <=50K')
(30, ' Private', 175856, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' <=50K')
(59, ' Private', 75867, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(34, ' Private', 134737, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 55, ' United-States', ' >50K')
(48, ' Private', 47343, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(33, ' Private', 156192, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(29, ' Private', 216481, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' >50K')
(55, ' Private', 185459, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(59, ' Private', 108496, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(39, ' Private', 165215, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1902, 18, ' United-States', ' >50K')
(39, ' Private', 179731, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 2415, 65, ' United-States', ' >50K')
(42, ' Private', 356934, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(37, ' Private', 108140, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 45, ' United-States', ' >50K')
(47, ' Private', 586657, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' Japan', ' >50K')
(45, ' Private', 360393, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' United-States', ' >50K')
(33, ' Private', 196385, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 37, ' United-States', ' >50K')
(50, ' Private', 108435, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 99999, 0, 60, ' United-States', ' >50K')
(33, ' Private', 394447, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 33, ' United-States', ' >50K')
(33, ' Private', 296453, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(46, ' Private', 117849, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(48, ' Private', 355978, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(47, ' Private', 148995, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 65, ' United-States', ' >50K')
(59, ' Private', 232672, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(41, ' Private', 101593, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(40, ' Private', 259307, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(37, ' Private', 218490, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' El-Salvador', ' >50K')
(52, ' Private', 108435, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' Greece', ' >50K')
(49, ' Private', 170871, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(49, ' Private', 180532, ' Masters', 14, ' Married-spouse-absent', ' Prof-specialty', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(46, ' Private', 155489, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(35, ' Private', 308691, ' Masters', 14, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 48, ' United-States', ' <=50K')
(43, ' Private', 220776, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 35, ' United-States', ' >50K')
(45, ' Private', 188950, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(32, ' Private', 191856, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Wife', ' White', ' Female', 0, 0, 45, ' United-States', ' >50K')
(61, ' Private', 119986, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' ?', ' >50K')
(36, ' Private', 269722, ' Masters', 14, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(36, ' Private', 237943, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(60, ' Private', 355865, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(54, ' Private', 421561, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(46, ' Private', 178829, ' Masters', 14, ' Married-spouse-absent', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 70, ' United-States', ' >50K')
(34, ' Private', 36385, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(49, ' Private', 181363, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(39, ' Private', 204501, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(38, ' Private', 192337, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' England', ' >50K')
(46, ' Private', 139268, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(51, ' Private', 102615, ' Masters', 14, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(51, ' Private', 63424, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' >50K')
(31, ' Private', 188246, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(40, ' Private', 226902, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(48, ' Private', 112906, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(55, ' Private', 208311, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1977, 20, ' United-States', ' >50K')
(39, ' Private', 230054, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(34, ' Private', 349169, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K')
(46, ' Private', 164733, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 41, ' United-States', ' <=50K')
(35, ' Private', 92028, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(29, ' Private', 53181, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(46, ' Private', 102771, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(66, ' Private', 116468, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 2936, 0, 20, ' United-States', ' <=50K')
(54, ' Private', 225599, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 7298, 0, 40, ' India', ' >50K')
(42, ' Private', 280167, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(41, ' Private', 173682, ' Masters', 14, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(45, ' Private', 216932, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 86648, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1977, 45, ' United-States', ' >50K')
(46, ' Private', 123053, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 50, ' Japan', ' >50K')
(49, ' Private', 122385, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 49020, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(42, ' Private', 173704, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(39, ' Private', 167140, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(57, ' Private', 437727, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1977, 45, ' United-States', ' >50K')
(44, ' Private', 120277, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' >50K')
(46, ' Private', 184169, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 7688, 0, 35, ' United-States', ' >50K')
(39, ' Private', 77005, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 99999, 0, 40, ' United-States', ' >50K')
(34, ' Private', 294064, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' France', ' <=50K')
(48, ' Private', 199058, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(45, ' Private', 129336, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(30, ' Private', 467108, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 44, ' United-States', ' >50K')
(33, ' Private', 144949, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 40, ' United-States', ' >50K')
(53, ' Private', 158294, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7298, 0, 40, ' United-States', ' >50K')
(45, ' Private', 199058, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 7298, 0, 50, ' United-States', ' >50K')
(46, ' Private', 273629, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(50, ' Private', 160724, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 7298, 0, 40, ' Philippines', ' >50K')
(47, ' Private', 121836, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 7688, 0, 38, ' United-States', ' >50K')
(59, ' Private', 333270, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 0, 35, ' Philippines', ' <=50K')
(30, ' Private', 340917, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 60, ' United-States', ' >50K')
(46, ' Private', 337050, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 45, ' United-States', ' >50K')
(42, ' Private', 203554, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(48, ' Private', 174386, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' El-Salvador', ' >50K')
(51, ' Private', 169112, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(52, ' Private', 74024, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(39, ' Private', 216552, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(28, ' Private', 204074, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 48, ' United-States', ' <=50K')
(41, ' Private', 101593, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(25, ' Private', 169100, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(41, ' Private', 177905, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')

(49, ' Private', 101825, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1977, 40, ' United-States', ' >50K')
(46, ' Private', 324655, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1902, 40, ' ?', ' >50K')
(53, ' Private', 114758, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 65, ' United-States', ' >50K')
(42, ' Private', 201785, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(43, ' Private', 304175, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(49, ' Private', 185041, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(53, ' Private', 424079, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 55, ' United-States', ' >50K')
(34, ' Private', 299635, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' United-States', ' >50K')
(42, ' Private', 107762, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(49, ' Private', 65087, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(37, ' Private', 117381, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(46, ' Private', 55720, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(55, ' Private', 31905, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(32, ' Private', 473133, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 225544, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 40, ' Poland', ' <=50K')
(46, ' Private', 265275, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(47, ' Private', 190139, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(44, ' Private', 116632, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(33, ' Private', 176992, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(44, ' Private', 296728, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(44, ' Private', 112517, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 20, ' United-States', ' >50K')
(29, ' Private', 168479, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(51, ' Private', 146574, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(37, ' Private', 126569, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(35, ' Private', 112271, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(49, ' Private', 178749, ' Masters', 14, ' Married-spouse-absent', ' Adm-clerical', ' Unmarried', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(53, ' Private', 106176, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 7298, 0, 60, ' United-States', ' >50K')
(46, ' Private', 137354, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' Philippines', ' >50K')
(35, ' Private', 241126, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 99357, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 15024, 0, 50, ' United-States', ' >50K')
(41, ' Private', 93793, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' >50K')
(50, ' Private', 196193, ' Masters', 14, ' Married-spouse-absent', ' Prof-specialty', ' Other-relative', ' White', ' Male', 0, 0, 60, ' ?', ' <=50K')
(66, ' Private', 216856, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(36, ' Private', 261382, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 15024, 0, 45, ' United-States', ' >50K')
(51, ' Private', 44000, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 99999, 0, 50, ' United-States', ' >50K')
(39, ' Private', 91711, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(40, ' Private', 146520, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(67, ' Private', 195161, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 20051, 0, 60, ' United-States', ' >50K')
(43, ' Private', 102180, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 126675, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(64, ' Private', 149044, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 2057, 60, ' China', ' <=50K')
(41, ' Private', 280167, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 70, ' United-States', ' >50K')
(55, ' Private', 163083, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(34, ' Private', 204470, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(39, ' Private', 194404, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 40, ' United-States', ' >50K')
(33, ' Private', 111567, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 45, ' Germany', ' >50K')
(38, ' Private', 314310, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(37, ' Private', 259785, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(45, ' Private', 127111, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(57, ' Private', 375868, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(44, ' Private', 104196, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(28, ' Private', 209205, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(30, ' Private', 110643, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 4386, 0, 40, ' United-States', ' >50K')
(41, ' Private', 174395, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(42, ' Private', 383493, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(38, ' Private', 241153, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 48, ' United-States', ' >50K')
(43, ' Private', 208277, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 45, ' United-States', ' >50K')
(44, ' Private', 115323, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(43, ' Private', 188808, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(44, ' Private', 125461, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 35, ' United-States', ' >50K')
(57, ' Private', 245193, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(51, ' Private', 182314, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 107302, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' India', ' <=50K')
(30, ' Private', 175856, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' <=50K')
(59, ' Private', 75867, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(34, ' Private', 134737, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 55, ' United-States', ' >50K')
(48, ' Private', 47343, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(33, ' Private', 156192, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(29, ' Private', 216481, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' >50K')
(55, ' Private', 185459, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(59, ' Private', 108496, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(39, ' Private', 165215, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1902, 18, ' United-States', ' >50K')
(39, ' Private', 179731, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 2415, 65, ' United-States', ' >50K')
(42, ' Private', 356934, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(37, ' Private', 108140, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 45, ' United-States', ' >50K')
(47, ' Private', 586657, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' Japan', ' >50K')
(45, ' Private', 360393, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' United-States', ' >50K')
(33, ' Private', 196385, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 37, ' United-States', ' >50K')
(50, ' Private', 108435, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 99999, 0, 60, ' United-States', ' >50K')
(33, ' Private', 394447, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 33, ' United-States', ' >50K')
(33, ' Private', 296453, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(46, ' Private', 117849, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(48, ' Private', 355978, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(47, ' Private', 148995, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 65, ' United-States', ' >50K')
(59, ' Private', 232672, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(41, ' Private', 101593, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(40, ' Private', 259307, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(37, ' Private', 218490, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' El-Salvador', ' >50K')
(52, ' Private', 108435, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' Greece', ' >50K')
(49, ' Private', 170871, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(49, ' Private', 180532, ' Masters', 14, ' Married-spouse-absent', ' Prof-specialty', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(46, ' Private', 155489, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(35, ' Private', 308691, ' Masters', 14, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 48, ' United-States', ' <=50K')
(43, ' Private', 220776, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 35, ' United-States', ' >50K')
(45, ' Private', 188950, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(32, ' Private', 191856, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Wife', ' White', ' Female', 0, 0, 45, ' United-States', ' >50K')
(61, ' Private', 119986, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' ?', ' >50K')
(36, ' Private', 269722, ' Masters', 14, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(36, ' Private', 237943, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(60, ' Private', 355865, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(54, ' Private', 421561, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(46, ' Private', 178829, ' Masters', 14, ' Married-spouse-absent', ' Exec-managerial', ' Not-in-family', ' White', ' Male', 0, 0, 70, ' United-States', ' >50K')
(34, ' Private', 36385, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(49, ' Private', 181363, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(39, ' Private', 204501, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(38, ' Private', 192337, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' England', ' >50K')
(46, ' Private', 139268, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(51, ' Private', 102615, ' Masters', 14, ' Married-civ-spouse', ' Protective-serv', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(51, ' Private', 63424, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' >50K')
(31, ' Private', 188246, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(40, ' Private', 226902, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(48, ' Private', 112906, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(55, ' Private', 208311, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1977, 20, ' United-States', ' >50K')
(39, ' Private', 230054, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(34, ' Private', 349169, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 40, ' Mexico', ' <=50K')
(46, ' Private', 164733, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 41, ' United-States', ' <=50K')
(35, ' Private', 92028, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(29, ' Private', 53181, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(46, ' Private', 102771, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(66, ' Private', 116468, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 2936, 0, 20, ' United-States', ' <=50K')
(54, ' Private', 225599, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 7298, 0, 40, ' India', ' >50K')
(42, ' Private', 280167, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(41, ' Private', 173682, ' Masters', 14, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(45, ' Private', 216932, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 86648, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1977, 45, ' United-States', ' >50K')
(46, ' Private', 123053, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 50, ' Japan', ' >50K')
(49, ' Private', 122385, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(35, ' Private', 49020, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(42, ' Private', 173704, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(39, ' Private', 167140, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(57, ' Private', 437727, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1977, 45, ' United-States', ' >50K')
(44, ' Private', 120277, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' >50K')

(28, ' Private', 51461, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(31, ' Private', 176185, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' France', ' >50K')
(45, ' Private', 154308, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 186183, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(28, ' Private', 319768, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 45, ' France', ' >50K')
(57, ' Private', 141570, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 1977, 40, ' United-States', ' >50K')
(40, ' Private', 111483, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(43, ' Private', 214781, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 5178, 0, 40, ' United-States', ' >50K')
(57, ' Private', 170287, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(42, ' Private', 169383, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(31, ' Private', 189759, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(50, ' Private', 168212, ' Masters', 14, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 1902, 45, ' United-States', ' >50K')
(34, ' Private', 88215, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 0, 40, ' China', ' >50K')
(38, ' Private', 103408, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 0, 40, ' ?', ' <=50K')
(37, ' Private', 340614, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(54, ' Private', 260052, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(36, ' Private', 198841, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(40, ' Private', 51290, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(48, ' Private', 233802, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Black', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(58, ' Private', 146477, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 40, ' Greece', ' >50K')
(57, ' Private', 191318, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(45, ' Private', 260490, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(53, ' Private', 229465, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(49, ' Private', 155489, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(34, ' Private', 163110, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(50, ' Private', 163948, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(49, ' Private', 138370, ' Masters', 14, ' Married-spouse-absent', ' Protective-serv', ' Not-in-family', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' India', ' <=50K')
(41, ' Private', 104892, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(36, ' Private', 126675, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1977, 50, ' United-States', ' >50K')
(42, ' Private', 183241, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 45, ' United-States', ' >50K')
(32, ' Private', 53277, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(50, ' Private', 206862, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 65, ' United-States', ' >50K')
(44, ' Private', 186916, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(44, ' Private', 104196, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(46, ' Private', 113390, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 1740, 60, ' United-States', ' <=50K')
(42, ' Private', 187720, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 15024, 0, 50, ' ?', ' >50K')
(31, ' Private', 263561, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(54, ' Private', 68985, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(47, ' Private', 120781, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 15024, 0, 40, ' ?', ' >50K')
(33, ' Private', 55291, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(57, ' Private', 112840, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(51, ' Private', 162238, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1887, 47, ' United-States', ' >50K')
(68, ' Private', 208478, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 18, ' ?', ' <=50K')
(53, ' Private', 123011, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(63, ' Private', 308028, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 5013, 0, 40, ' United-States', ' <=50K')
(38, ' Private', 320451, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' ?', ' <=50K')
(44, ' Private', 54310, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7298, 0, 40, ' United-States', ' >50K')
(46, ' Private', 197332, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 46, ' United-States', ' >50K')
(45, ' Private', 102308, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 60, ' United-States', ' >50K')
(54, ' Private', 215990, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1887, 44, ' United-States', ' >50K')
(48, ' Private', 287480, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 134367, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1977, 24, ' United-States', ' >50K')
(36, ' Private', 52327, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Other', ' Male', 0, 0, 40, ' Iran', ' >50K')
(28, ' Private', 192283, ' Masters', 14, ' Married-spouse-absent', ' Sales', ' Not-in-family', ' White', ' Female', 0, 0, 80, ' United-States', ' >50K')
(46, ' Private', 110171, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(45, ' Private', 33794, ' Masters', 14, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(67, ' Private', 105252, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(54, ' Private', 176240, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 7688, 0, 60, ' United-States', ' >50K')
(58, ' Private', 170108, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(49, ' Private', 185385, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(51, ' Private', 172046, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1977, 50, ' United-States', ' >50K')
(42, ' Private', 92288, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' ?', ' <=50K')
(28, ' Private', 109001, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 38, ' United-States', ' >50K')
(65, ' Private', 344152, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 5556, 0, 50, ' United-States', ' >50K')
(60, ' Private', 239576, ' Masters', 14, ' Married-civ-spouse', ' Transport-moving', ' Husband', ' White', ' Male', 0, 0, 10, ' United-States', ' <=50K')
(33, ' Private', 594187, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(26, ' Private', 173593, ' Masters', 14, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 20, ' Canada', ' <=50K')
(34, ' Private', 99872, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 3103, 0, 40, ' India', ' >50K')
(36, ' Private', 145576, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' White', ' Male', 0, 1977, 40, ' Japan', ' >50K')
(31, ' Private', 309620, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 6, ' South', ' <=50K')
(35, ' Private', 119098, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(43, ' Private', 183273, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 15024, 0, 32, ' United-States', ' >50K')
(49, ' Private', 340755, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(52, ' Private', 260938, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(49, ' Private', 129513, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(47, ' Private', 102628, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 55, ' United-States', ' >50K')
(63, ' Private', 30813, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(38, ' Private', 300975, ' Masters', 14, ' Married-civ-spouse', ' Other-service', ' Husband', ' Black', ' Male', 0, 1485, 40, ' ?', ' <=50K')
(35, ' Private', 160120, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 50, ' United-States', ' >50K')
(51, ' Private', 48343, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 7298, 0, 50, ' United-States', ' >50K')
(33, ' Private', 188246, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 7298, 0, 45, ' United-States', ' >50K')
(29, ' Private', 162551, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Asian-Pac-Islander', ' Female', 0, 0, 40, ' Hong', ' >50K')
(41, ' Private', 242089, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(41, ' Private', 56795, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 45, ' England', ' <=50K')
(51, ' Private', 123429, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(39, ' Private', 108140, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(44, ' Private', 165346, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(34, ' Private', 379798, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(38, ' Private', 227945, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 99999, 0, 65, ' United-States', ' >50K')
(61, ' Private', 80896, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 45, ' India', ' >50K')
(38, ' Private', 98360, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(48, ' Private', 207277, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 40, ' United-States', ' >50K')
(56, ' Private', 37394, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(47, ' Private', 181363, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(54, ' Private', 338620, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 52, ' United-States', ' >50K')
(68, ' Private', 211287, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 2392, 40, ' United-States', ' >50K')
(30, ' Private', 169496, ' Masters', 14, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 15, ' United-States', ' >50K')
(53, ' Private', 22978, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 50, ' United-States', ' >50K')
(41, ' Private', 211253, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' >50K')
(36, ' Private', 171393, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7298, 0, 55, ' United-States', ' >50K')
(32, ' Private', 209538, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' >50K')
(36, ' Private', 223433, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 7688, 0, 50, ' United-States', ' >50K')
(54, ' Private', 98436, ' Masters', 14, ' Married-civ-spouse', ' Other-service', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(28, ' Private', 173944, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(46, ' Private', 261059, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1977, 50, ' United-States', ' >50K')
(42, ' Private', 198341, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 1902, 55, ' India', ' >50K')
(53, ' Private', 70387, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 4386, 0, 40, ' India', ' >50K')
(47, ' Private', 158286, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(34, ' Private', 165737, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 43, ' India', ' >50K')
(51, ' Private', 82578, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 38, ' Canada', ' >50K')
(63, ' Private', 167967, ' Masters', 14, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' White', ' Male', 0, 0, 46, ' United-States', ' <=50K')
(48, ' Private', 148995, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(36, ' Private', 386726, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 1977, 44, ' United-States', ' >50K')
(48, ' Private', 254291, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(37, ' Private', 174150, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(48, ' Private', 204629, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(51, ' Private', 123053, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 5013, 0, 40, ' India', ' <=50K')
(61, ' Private', 147280, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' United-States', ' >50K')
(35, ' Private', 206951, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(46, ' Private', 268022, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 55, ' ?', ' >50K')
(56, ' Private', 282023, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(33, ' Private', 181372, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 50, ' United-States', ' >50K')
(54, ' Private', 139850, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 45, ' United-States', ' >50K')
(38, ' Private', 277248, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 60, ' Cuba', ' >50K')
(59, ' Private', 81973, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' United-States', ' >50K')
(33, ' Private', 79923, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(53, ' Private', 285621, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' >50K')
(49, ' Private', 187370, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 50, ' United-States', ' >50K')
(50, ' Private', 22211, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 50, ' United-States', ' >50K')
(47, ' Private', 158451, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 2, ' United-States', ' >50K')
(27, ' Private', 115945, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(38, ' Private', 91039, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 65, ' United-States', ' >50K')

(53, ' Private', 110977, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 1902, 50, ' United-States', ' >50K')
(67, ' Private', 94610, ' Masters', 14, ' Married-civ-spouse', ' Sales', ' Husband', ' White', ' Male', 0, 0, 30, ' United-States', ' >50K')
(38, ' Private', 185848, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 99999, 0, 70, ' United-States', ' >50K')
(49, ' Private', 193366, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 65, ' United-States', ' >50K')
(26, ' Private', 76491, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(30, ' Private', 122042, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(60, ' Private', 85995, ' Masters', 14, ' Married-civ-spouse', ' Adm-clerical', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 50, ' South', ' >50K')
(23, ' Private', 143003, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 1887, 50, ' India', ' >50K')
(50, ' Private', 201882, ' Masters', 14, ' Married-civ-spouse', ' Machine-op-inspct', ' Husband', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(44, ' Private', 267717, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 42, ' United-States', ' >50K')
(30, ' Private', 182771, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' United-States', ' >50K')
(39, ' Private', 198841, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 7688, 0, 45, ' United-States', ' >50K')
(53, ' Private', 53197, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 3103, 0, 40, ' United-States', ' >50K')
(55, ' Private', 70088, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(36, ' Private', 199346, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 50, ' United-States', ' >50K')
(30, ' Private', 378009, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(35, ' Private', 75855, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Black', ' Male', 7298, 0, 40, ' ?', ' >50K')
(59, ' Private', 59469, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' White', ' Male', 0, 0, 40, ' Iran', ' <=50K')
(39, ' Private', 72338, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' Philippines', ' >50K')
(50, ' Private', 176157, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' >50K')
(30, ' Private', 341051, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 15024, 0, 60, ' United-States', ' >50K')
(43, ' Private', 346321, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 45, ' United-States', ' >50K')
(47, ' Private', 155664, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 99999, 0, 55, ' United-States', ' >50K')
(48, ' Private', 379883, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' Cuba', ' >50K')
(49, ' Private', 123681, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 43, ' United-States', ' >50K')
(43, ' Private', 174295, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' <=50K')
(32, ' Private', 313835, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(40, ' Private', 137225, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(25, ' Private', 178025, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(31, ' Private', 183801, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 1902, 43, ' United-States', ' >50K')
(61, ' Private', 232719, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(41, ' Private', 122215, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 15024, 0, 40, ' United-States', ' >50K')
(33, ' Private', 139057, ' Masters', 14, ' Married-civ-spouse', ' Tech-support', ' Husband', ' Asian-Pac-Islander', ' Male', 0, 0, 50, ' United-States', ' >50K')
(34, ' Private', 30673, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Husband', ' White', ' Male', 0, 0, 55, ' United-States', ' <=50K')
(41, ' Private', 201495, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')
(46, ' Private', 42972, ' Masters', 14, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' White', ' Female', 0, 0, 22, ' United-States', ' >50K')
(53, ' Private', 321865, ' Masters', 14, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 40, ' United-States', ' >50K')

5. What is the average, minimum and maximum age group for people working in
different sectors

In [28]:
str='''select occupation,avg(age),min(age),max(age)  from sqladb group by occupation'''
for rec in con.execute(str):
    print(rec)

(' ?', 40.882799782962564, 17, 90)
(' Adm-clerical', 36.96445623342175, 17, 90)
(' Armed-Forces', 30.22222222222222, 23, 46)
(' Craft-repair', 39.03147109050988, 17, 90)
(' Exec-managerial', 42.16920806689621, 17, 90)
(' Farming-fishing', 41.2112676056338, 17, 90)
(' Handlers-cleaners', 32.16569343065694, 17, 90)
(' Machine-op-inspct', 37.71528471528472, 17, 90)
(' Other-service', 34.94962063732929, 17, 90)
(' Priv-house-serv', 41.7248322147651, 17, 81)
(' Prof-specialty', 40.51763285024155, 17, 90)
(' Protective-serv', 38.9537750385208, 17, 90)
(' Sales', 37.353972602739724, 17, 90)
(' Tech-support', 37.022629310344826, 17, 73)
(' Transport-moving', 40.19787100814026, 17, 90)

6. Calculate age distribution by country

In [36]:
str='''select "native-country", age, count(*) from sqladb group by "native-country", age order by 1 desc'''
for rec in con.execute(str):
    print(rec)

(' Yugoslavia', 20, 2)
(' Yugoslavia', 22, 2)
(' Yugoslavia', 25, 2)
(' Yugoslavia', 29, 2)
(' Yugoslavia', 31, 2)
(' Yugoslavia', 35, 4)
(' Yugoslavia', 36, 2)
(' Yugoslavia', 40, 2)
(' Yugoslavia', 41, 4)
(' Yugoslavia', 43, 2)
(' Yugoslavia', 45, 2)
(' Yugoslavia', 56, 4)
(' Yugoslavia', 66, 2)
(' Vietnam', 19, 4)
(' Vietnam', 20, 6)
(' Vietnam', 21, 6)
(' Vietnam', 22, 6)
(' Vietnam', 23, 20)
(' Vietnam', 24, 4)
(' Vietnam', 25, 6)
(' Vietnam', 26, 2)
(' Vietnam', 27, 2)
(' Vietnam', 29, 2)
(' Vietnam', 30, 16)
(' Vietnam', 31, 4)
(' Vietnam', 33, 2)
(' Vietnam', 35, 4)
(' Vietnam', 36, 2)
(' Vietnam', 37, 4)
(' Vietnam', 38, 2)
(' Vietnam', 40, 2)
(' Vietnam', 41, 2)
(' Vietnam', 43, 4)
(' Vietnam', 44, 6)
(' Vietnam', 45, 6)
(' Vietnam', 46, 2)
(' Vietnam', 48, 2)
(' Vietnam', 50, 2)
(' Vietnam', 51, 2)
(' Vietnam', 52, 2)
(' Vietnam', 53, 2)
(' Vietnam', 54, 2)
(' Vietnam', 63, 2)
(' Vietnam', 70, 2)
(' Vietnam', 73, 4)
(' United-States', 17, 748)
(' United-States', 18, 1048)
(' United-States', 19, 1318)
(' United-States', 20, 1378)
(' United-States', 21, 1302)
(' United-States', 22, 1366)
(' United-States', 23, 1542)
(' United-States', 24, 1410)
(' United-States', 25, 1468)
(' United-States', 26, 1388)
(' United-States', 27, 1454)
(' United-States', 28, 1502)
(' United-States', 29, 1412)
(' United-States', 30, 1498)
(' United-States', 31, 1570)
(' United-States', 32, 1468)
(' United-States', 33, 1546)
(' United-States', 34, 1568)
(' United-States', 35, 1578)
(' United-States', 36, 1602)
(' United-States', 37, 1524)
(' United-States', 38, 1482)
(' United-States', 39, 1466)
(' United-States', 40, 1442)
(' United-States', 41, 1410)
(' United-States', 42, 1402)
(' United-States', 43, 1390)
(' United-States', 44, 1316)
(' United-States', 45, 1306)
(' United-States', 46, 1328)
(' United-States', 47, 1262)
(' United-States', 48, 966)
(' United-States', 49, 1062)
(' United-States', 50, 1086)
(' United-States', 51, 1098)
(' United-States', 52, 858)
(' United-States', 53, 816)
(' United-States', 54, 740)
(' United-States', 55, 760)
(' United-States', 56, 652)
(' United-States', 57, 632)
(' United-States', 58, 680)
(' United-States', 59, 644)
(' United-States', 60, 572)
(' United-States', 61, 546)
(' United-States', 62, 478)
(' United-States', 63, 422)
(' United-States', 64, 378)
(' United-States', 65, 326)
(' United-States', 66, 270)
(' United-States', 67, 282)
(' United-States', 68, 222)
(' United-States', 69, 204)
(' United-States', 70, 166)
(' United-States', 71, 138)
(' United-States', 72, 120)
(' United-States', 73, 112)
(' United-States', 74, 96)
(' United-States', 75, 84)
(' United-States', 76, 88)
(' United-States', 77, 54)
(' United-States', 78, 40)
(' United-States', 79, 40)
(' United-States', 80, 42)
(' United-States', 81, 30)
(' United-States', 82, 22)
(' United-States', 83, 12)
(' United-States', 84, 20)
(' United-States', 85, 4)
(' United-States', 86, 2)
(' United-States', 87, 2)
(' United-States', 88, 6)
(' United-States', 90, 74)
(' Trinadad&Tobago', 17, 2)
(' Trinadad&Tobago', 28, 2)
(' Trinadad&Tobago', 31, 2)
(' Trinadad&Tobago', 32, 2)
(' Trinadad&Tobago', 33, 2)
(' Trinadad&Tobago', 35, 2)
(' Trinadad&Tobago', 38, 4)
(' Trinadad&Tobago', 40, 2)
(' Trinadad&Tobago', 42, 2)
(' Trinadad&Tobago', 43, 2)
(' Trinadad&Tobago', 45, 4)
(' Trinadad&Tobago', 46, 2)
(' Trinadad&Tobago', 48, 2)
(' Trinadad&Tobago', 50, 2)
(' Trinadad&Tobago', 56, 2)
(' Trinadad&Tobago', 57, 2)
(' Trinadad&Tobago', 61, 2)
(' Thailand', 19, 4)
(' Thailand', 22, 2)
(' Thailand', 24, 2)
(' Thailand', 26, 2)
(' Thailand', 29, 2)
(' Thailand', 30, 2)
(' Thailand', 31, 2)
(' Thailand', 33, 4)
(' Thailand', 37, 2)
(' Thailand', 43, 4)
(' Thailand', 45, 2)
(' Thailand', 46, 2)
(' Thailand', 47, 4)
(' Thailand', 55, 2)
(' Taiwan', 20, 2)
(' Taiwan', 21, 2)
(' Taiwan', 22, 4)
(' Taiwan', 23, 2)
(' Taiwan', 24, 4)
(' Taiwan', 25, 6)
(' Taiwan', 26, 4)
(' Taiwan', 27, 2)
(' Taiwan', 28, 4)
(' Taiwan', 29, 8)
(' Taiwan', 30, 10)
(' Taiwan', 31, 4)
(' Taiwan', 32, 2)
(' Taiwan', 33, 2)
(' Taiwan', 34, 4)
(' Taiwan', 35, 6)
(' Taiwan', 36, 6)
(' Taiwan', 38, 2)
(' Taiwan', 40, 2)
(' Taiwan', 41, 8)
(' Taiwan', 42, 6)
(' Taiwan', 44, 2)
(' Taiwan', 47, 2)
(' Taiwan', 51, 2)
(' Taiwan', 57, 4)
(' Taiwan', 61, 2)
(' South', 19, 6)
(' South', 20, 4)
(' South', 21, 2)
(' South', 22, 10)
(' South', 23, 6)
(' South', 24, 6)
(' South', 26, 6)
(' South', 27, 4)
(' South', 28, 2)
(' South', 29, 4)
(' South', 30, 6)
(' South', 31, 6)
(' South', 32, 4)
(' South', 33, 4)
(' South', 34, 4)
(' South', 35, 2)
(' South', 36, 8)
(' South', 37, 4)
(' South', 39, 2)
(' South', 40, 2)
(' South', 42, 4)
(' South', 43, 6)
(' South', 44, 2)
(' South', 45, 6)
(' South', 46, 2)
(' South', 47, 2)
(' South', 48, 4)
(' South', 49, 4)
(' South', 50, 8)
(' South', 51, 2)
(' South', 53, 2)
(' South', 54, 4)
(' South', 57, 4)
(' South', 58, 2)
(' South', 60, 4)
(' South', 61, 2)
(' South', 62, 2)
(' South', 63, 4)
(' South', 78, 2)
(' South', 90, 2)
(' Scotland', 18, 2)
(' Scotland', 27, 2)
(' Scotland', 29, 4)
(' Scotland', 38, 2)
(' Scotland', 40, 2)
(' Scotland', 42, 2)
(' Scotland', 47, 2)
(' Scotland', 49, 2)
(' Scotland', 51, 2)
(' Scotland', 53, 2)
(' Scotland', 62, 2)
(' Puerto-Rico', 17, 2)
(' Puerto-Rico', 19, 6)
(' Puerto-Rico', 20, 4)
(' Puerto-Rico', 21, 2)
(' Puerto-Rico', 22, 2)
(' Puerto-Rico', 23, 10)
(' Puerto-Rico', 24, 2)
(' Puerto-Rico', 25, 2)
(' Puerto-Rico', 26, 6)
(' Puerto-Rico', 27, 4)
(' Puerto-Rico', 28, 8)
(' Puerto-Rico', 29, 2)
(' Puerto-Rico', 30, 4)
(' Puerto-Rico', 31, 8)
(' Puerto-Rico', 32, 4)
(' Puerto-Rico', 33, 4)
(' Puerto-Rico', 34, 4)
(' Puerto-Rico', 35, 12)
(' Puerto-Rico', 36, 4)
(' Puerto-Rico', 37, 8)
(' Puerto-Rico', 38, 2)
(' Puerto-Rico', 39, 6)
(' Puerto-Rico', 40, 10)
(' Puerto-Rico', 41, 4)
(' Puerto-Rico', 42, 16)
(' Puerto-Rico', 43, 2)
(' Puerto-Rico', 44, 8)
(' Puerto-Rico', 45, 2)
(' Puerto-Rico', 46, 4)
(' Puerto-Rico', 47, 16)
(' Puerto-Rico', 48, 2)
(' Puerto-Rico', 49, 6)
(' Puerto-Rico', 50, 6)
(' Puerto-Rico', 51, 2)
(' Puerto-Rico', 52, 4)
(' Puerto-Rico', 53, 6)
(' Puerto-Rico', 54, 4)
(' Puerto-Rico', 55, 2)
(' Puerto-Rico', 56, 2)
(' Puerto-Rico', 57, 4)
(' Puerto-Rico', 59, 6)
(' Puerto-Rico', 60, 2)
(' Puerto-Rico', 61, 4)
(' Puerto-Rico', 64, 2)
(' Puerto-Rico', 66, 4)
(' Puerto-Rico', 70, 2)
(' Puerto-Rico', 90, 2)
(' Portugal', 19, 2)
(' Portugal', 21, 2)
(' Portugal', 22, 2)
(' Portugal', 23, 2)
(' Portugal', 24, 2)
(' Portugal', 26, 2)
(' Portugal', 27, 2)
(' Portugal', 28, 4)
(' Portugal', 29, 2)
(' Portugal', 30, 2)
(' Portugal', 31, 2)
(' Portugal', 33, 2)
(' Portugal', 34, 6)
(' Portugal', 37, 4)
(' Portugal', 38, 6)
(' Portugal', 43, 4)
(' Portugal', 44, 2)
(' Portugal', 46, 2)
(' Portugal', 47, 2)
(' Portugal', 48, 2)
(' Portugal', 49, 4)
(' Portugal', 51, 2)
(' Portugal', 56, 4)
(' Portugal', 57, 4)
(' Portugal', 63, 2)
(' Portugal', 73, 2)
(' Portugal', 78, 2)
(' Poland', 17, 2)
(' Poland', 21, 2)
(' Poland', 23, 4)
(' Poland', 25, 6)
(' Poland', 26, 4)
(' Poland', 27, 4)
(' Poland', 28, 4)
(' Poland', 29, 2)
(' Poland', 30, 4)
(' Poland', 31, 2)
(' Poland', 35, 4)
(' Poland', 38, 8)
(' Poland', 39, 10)
(' Poland', 40, 2)
(' Poland', 41, 4)
(' Poland', 42, 4)
(' Poland', 43, 6)
(' Poland', 44, 6)
(' Poland', 45, 2)
(' Poland', 48, 2)
(' Poland', 49, 2)
(' Poland', 50, 2)
(' Poland', 52, 2)
(' Poland', 53, 2)
(' Poland', 54, 2)
(' Poland', 55, 4)
(' Poland', 57, 4)
(' Poland', 58, 2)
(' Poland', 59, 2)
(' Poland', 60, 4)
(' Poland', 61, 2)
(' Poland', 71, 2)
(' Poland', 73, 2)
(' Poland', 79, 2)
(' Poland', 81, 2)
(' Poland', 85, 2)
(' Philippines', 17, 2)
(' Philippines', 18, 4)
(' Philippines', 19, 4)
(' Philippines', 20, 4)
(' Philippines', 21, 2)
(' Philippines', 22, 8)
(' Philippines', 23, 12)
(' Philippines', 24, 10)
(' Philippines', 25, 6)
(' Philippines', 26, 12)
(' Philippines', 27, 22)
(' Philippines', 28, 10)
(' Philippines', 29, 12)
(' Philippines', 30, 4)
(' Philippines', 31, 6)
(' Philippines', 32, 6)
(' Philippines', 33, 12)
(' Philippines', 34, 14)
(' Philippines', 35, 16)
(' Philippines', 36, 6)
(' Philippines', 37, 16)
(' Philippines', 38, 14)
(' Philippines', 39, 28)
(' Philippines', 40, 6)
(' Philippines', 41, 8)
(' Philippines', 42, 8)
(' Philippines', 43, 6)
(' Philippines', 44, 6)
(' Philippines', 45, 14)
(' Philippines', 46, 14)
(' Philippines', 47, 4)
(' Philippines', 48, 10)
(' Philippines', 49, 8)
(' Philippines', 50, 16)
(' Philippines', 51, 2)
(' Philippines', 52, 4)
(' Philippines', 53, 4)
(' Philippines', 54, 4)
(' Philippines', 55, 6)
(' Philippines', 56, 2)
(' Philippines', 57, 4)
(' Philippines', 58, 4)
(' Philippines', 59, 4)
(' Philippines', 60, 4)
(' Philippines', 61, 2)
(' Philippines', 62, 4)
(' Philippines', 63, 4)
(' Philippines', 64, 2)
(' Philippines', 66, 4)
(' Philippines', 67, 2)
(' Philippines', 69, 2)
(' Philippines', 70, 2)
(' Philippines', 73, 2)
(' Philippines', 75, 2)
(' Philippines', 90, 2)
(' Peru', 17, 4)
(' Peru', 18, 2)
(' Peru', 20, 2)
(' Peru', 21, 2)
(' Peru', 22, 2)
(' Peru', 23, 2)
(' Peru', 24, 2)
(' Peru', 25, 2)
(' Peru', 26, 2)
(' Peru', 27, 2)
(' Peru', 29, 2)

(' Peru', 30, 2)
(' Peru', 33, 4)
(' Peru', 34, 2)
(' Peru', 35, 2)
(' Peru', 37, 2)
(' Peru', 41, 10)
(' Peru', 44, 2)
(' Peru', 46, 2)
(' Peru', 48, 4)
(' Peru', 49, 4)
(' Peru', 64, 2)
(' Peru', 69, 2)
(' Outlying-US(Guam-USVI-etc)', 21, 2)
(' Outlying-US(Guam-USVI-etc)', 23, 2)
(' Outlying-US(Guam-USVI-etc)', 25, 2)
(' Outlying-US(Guam-USVI-etc)', 26, 2)
(' Outlying-US(Guam-USVI-etc)', 29, 4)
(' Outlying-US(Guam-USVI-etc)', 30, 2)
(' Outlying-US(Guam-USVI-etc)', 41, 2)
(' Outlying-US(Guam-USVI-etc)', 43, 2)
(' Outlying-US(Guam-USVI-etc)', 47, 4)
(' Outlying-US(Guam-USVI-etc)', 59, 4)
(' Outlying-US(Guam-USVI-etc)', 63, 2)
(' Nicaragua', 19, 4)
(' Nicaragua', 20, 8)
(' Nicaragua', 21, 2)
(' Nicaragua', 25, 2)
(' Nicaragua', 26, 2)
(' Nicaragua', 27, 2)
(' Nicaragua', 28, 4)
(' Nicaragua', 29, 4)
(' Nicaragua', 30, 4)
(' Nicaragua', 32, 6)
(' Nicaragua', 33, 2)
(' Nicaragua', 34, 2)
(' Nicaragua', 36, 2)
(' Nicaragua', 37, 2)
(' Nicaragua', 38, 2)
(' Nicaragua', 39, 2)
(' Nicaragua', 41, 2)
(' Nicaragua', 42, 2)
(' Nicaragua', 43, 4)
(' Nicaragua', 44, 2)
(' Nicaragua', 48, 2)
(' Nicaragua', 55, 2)
(' Nicaragua', 56, 2)
(' Nicaragua', 67, 2)
(' Mexico', 17, 12)
(' Mexico', 18, 12)
(' Mexico', 19, 28)
(' Mexico', 20, 36)
(' Mexico', 21, 48)
(' Mexico', 22, 48)
(' Mexico', 23, 64)
(' Mexico', 24, 50)
(' Mexico', 25, 78)
(' Mexico', 26, 44)
(' Mexico', 27, 54)
(' Mexico', 28, 66)
(' Mexico', 29, 34)
(' Mexico', 30, 42)
(' Mexico', 31, 66)
(' Mexico', 32, 42)
(' Mexico', 33, 44)
(' Mexico', 34, 24)
(' Mexico', 35, 30)
(' Mexico', 36, 36)
(' Mexico', 37, 38)
(' Mexico', 38, 30)
(' Mexico', 39, 24)
(' Mexico', 40, 22)
(' Mexico', 41, 40)
(' Mexico', 42, 14)
(' Mexico', 43, 32)
(' Mexico', 44, 20)
(' Mexico', 45, 18)
(' Mexico', 46, 20)
(' Mexico', 47, 20)
(' Mexico', 48, 14)
(' Mexico', 49, 6)
(' Mexico', 50, 8)
(' Mexico', 51, 14)
(' Mexico', 52, 16)
(' Mexico', 53, 14)
(' Mexico', 54, 16)
(' Mexico', 55, 6)
(' Mexico', 56, 6)
(' Mexico', 57, 10)
(' Mexico', 58, 10)
(' Mexico', 59, 4)
(' Mexico', 60, 6)
(' Mexico', 61, 8)
(' Mexico', 62, 2)
(' Mexico', 63, 2)
(' Mexico', 65, 4)
(' Mexico', 74, 2)
(' Mexico', 81, 2)
(' Laos', 19, 4)
(' Laos', 23, 2)
(' Laos', 24, 2)
(' Laos', 27, 4)
(' Laos', 29, 4)
(' Laos', 30, 2)
(' Laos', 32, 2)
(' Laos', 36, 4)
(' Laos', 42, 2)
(' Laos', 44, 2)
(' Laos', 49, 2)
(' Laos', 50, 2)
(' Laos', 53, 2)
(' Laos', 56, 2)
(' Japan', 19, 4)
(' Japan', 24, 2)
(' Japan', 25, 2)
(' Japan', 26, 4)
(' Japan', 27, 6)
(' Japan', 29, 8)
(' Japan', 30, 2)
(' Japan', 31, 2)
(' Japan', 32, 2)
(' Japan', 33, 8)
(' Japan', 34, 4)
(' Japan', 35, 4)
(' Japan', 36, 6)
(' Japan', 37, 6)
(' Japan', 38, 4)
(' Japan', 39, 6)
(' Japan', 40, 4)
(' Japan', 41, 10)
(' Japan', 43, 2)
(' Japan', 44, 4)
(' Japan', 45, 6)
(' Japan', 46, 2)
(' Japan', 47, 8)
(' Japan', 48, 4)
(' Japan', 50, 2)
(' Japan', 52, 2)
(' Japan', 53, 4)
(' Japan', 54, 2)
(' Japan', 56, 2)
(' Japan', 61, 2)
(' Jamaica', 18, 2)
(' Jamaica', 19, 2)
(' Jamaica', 21, 6)
(' Jamaica', 22, 6)
(' Jamaica', 23, 4)
(' Jamaica', 24, 8)
(' Jamaica', 25, 8)
(' Jamaica', 26, 6)
(' Jamaica', 27, 8)
(' Jamaica', 28, 10)
(' Jamaica', 29, 4)
(' Jamaica', 30, 2)
(' Jamaica', 31, 6)
(' Jamaica', 32, 6)
(' Jamaica', 33, 4)
(' Jamaica', 34, 8)
(' Jamaica', 35, 8)
(' Jamaica', 36, 2)
(' Jamaica', 37, 2)
(' Jamaica', 38, 2)
(' Jamaica', 39, 4)
(' Jamaica', 40, 4)
(' Jamaica', 41, 4)
(' Jamaica', 42, 2)
(' Jamaica', 43, 2)
(' Jamaica', 44, 6)
(' Jamaica', 46, 2)
(' Jamaica', 47, 2)
(' Jamaica', 48, 4)
(' Jamaica', 49, 2)
(' Jamaica', 50, 2)
(' Jamaica', 51, 4)
(' Jamaica', 53, 4)
(' Jamaica', 54, 4)
(' Jamaica', 55, 2)
(' Jamaica', 56, 2)
(' Jamaica', 57, 2)
(' Jamaica', 59, 2)
(' Jamaica', 65, 2)
(' Jamaica', 66, 2)
(' Italy', 19, 2)
(' Italy', 20, 2)
(' Italy', 21, 2)
(' Italy', 22, 2)
(' Italy', 24, 2)
(' Italy', 25, 4)
(' Italy', 28, 2)
(' Italy', 29, 2)
(' Italy', 31, 6)
(' Italy', 32, 4)
(' Italy', 33, 2)
(' Italy', 34, 2)
(' Italy', 36, 4)
(' Italy', 38, 8)
(' Italy', 39, 2)
(' Italy', 41, 4)
(' Italy', 42, 6)
(' Italy', 43, 2)
(' Italy', 44, 4)
(' Italy', 46, 2)
(' Italy', 47, 8)
(' Italy', 48, 6)
(' Italy', 49, 4)
(' Italy', 50, 4)
(' Italy', 51, 2)
(' Italy', 53, 10)
(' Italy', 54, 4)
(' Italy', 55, 4)
(' Italy', 56, 4)
(' Italy', 57, 4)
(' Italy', 58, 2)
(' Italy', 59, 8)
(' Italy', 60, 2)
(' Italy', 61, 4)
(' Italy', 62, 2)
(' Italy', 64, 2)
(' Italy', 65, 4)
(' Italy', 68, 4)
(' Italy', 69, 2)
(' Italy', 77, 2)
(' Ireland', 23, 4)
(' Ireland', 27, 4)
(' Ireland', 29, 2)
(' Ireland', 30, 8)
(' Ireland', 31, 2)
(' Ireland', 32, 8)
(' Ireland', 34, 2)
(' Ireland', 35, 2)
(' Ireland', 40, 4)
(' Ireland', 46, 2)
(' Ireland', 48, 2)
(' Ireland', 50, 2)
(' Ireland', 51, 2)
(' Ireland', 55, 2)
(' Ireland', 68, 2)
(' Iran', 22, 4)
(' Iran', 23, 2)
(' Iran', 24, 2)
(' Iran', 29, 2)
(' Iran', 30, 4)
(' Iran', 32, 6)
(' Iran', 33, 2)
(' Iran', 34, 4)
(' Iran', 35, 4)
(' Iran', 36, 8)
(' Iran', 37, 4)
(' Iran', 38, 6)
(' Iran', 39, 2)
(' Iran', 40, 4)
(' Iran', 41, 4)
(' Iran', 42, 2)
(' Iran', 43, 2)
(' Iran', 44, 2)
(' Iran', 45, 2)
(' Iran', 47, 6)
(' Iran', 51, 2)
(' Iran', 52, 2)
(' Iran', 56, 2)
(' Iran', 57, 2)
(' Iran', 59, 2)
(' Iran', 62, 2)
(' Iran', 63, 2)
(' India', 17, 2)
(' India', 18, 2)
(' India', 20, 2)
(' India', 21, 2)
(' India', 22, 4)
(' India', 23, 2)
(' India', 24, 4)
(' India', 25, 6)
(' India', 26, 6)
(' India', 27, 8)
(' India', 28, 6)
(' India', 29, 8)
(' India', 30, 10)
(' India', 31, 10)
(' India', 32, 6)
(' India', 33, 6)
(' India', 34, 8)
(' India', 35, 8)
(' India', 36, 6)
(' India', 38, 4)
(' India', 39, 2)
(' India', 40, 2)
(' India', 41, 6)
(' India', 42, 6)
(' India', 43, 6)
(' India', 44, 2)
(' India', 45, 8)
(' India', 46, 6)
(' India', 47, 4)
(' India', 48, 8)
(' India', 49, 4)
(' India', 50, 2)
(' India', 51, 4)
(' India', 52, 2)
(' India', 53, 4)
(' India', 54, 6)
(' India', 55, 4)
(' India', 57, 4)
(' India', 58, 2)
(' India', 59, 4)
(' India', 61, 4)
(' Hungary', 24, 2)
(' Hungary', 26, 2)
(' Hungary', 28, 2)
(' Hungary', 30, 2)
(' Hungary', 47, 2)
(' Hungary', 49, 2)
(' Hungary', 54, 2)
(' Hungary', 55, 2)
(' Hungary', 57, 2)
(' Hungary', 60, 2)
(' Hungary', 65, 2)
(' Hungary', 66, 2)
(' Hungary', 81, 2)
(' Hong', 19, 2)
(' Hong', 26, 4)
(' Hong', 27, 4)
(' Hong', 28, 4)
(' Hong', 29, 2)
(' Hong', 30, 2)
(' Hong', 32, 2)
(' Hong', 33, 4)
(' Hong', 35, 2)
(' Hong', 36, 2)
(' Hong', 37, 4)
(' Hong', 40, 2)
(' Hong', 41, 2)
(' Hong', 49, 2)
(' Hong', 60, 2)
(' Honduras', 18, 2)
(' Honduras', 19, 2)
(' Honduras', 26, 2)
(' Honduras', 28, 4)
(' Honduras', 30, 2)
(' Honduras', 31, 4)
(' Honduras', 36, 2)
(' Honduras', 41, 2)
(' Honduras', 47, 4)
(' Honduras', 58, 2)
(' Holand-Netherlands', 32, 2)
(' Haiti', 17, 2)
(' Haiti', 19, 2)
(' Haiti', 20, 2)
(' Haiti', 22, 4)
(' Haiti', 23, 4)
(' Haiti', 24, 4)
(' Haiti', 28, 4)
(' Haiti', 29, 4)
(' Haiti', 30, 2)
(' Haiti', 32, 2)
(' Haiti', 33, 4)
(' Haiti', 34, 2)
(' Haiti', 35, 2)
(' Haiti', 36, 4)
(' Haiti', 38, 4)
(' Haiti', 40, 2)
(' Haiti', 41, 2)
(' Haiti', 42, 4)
(' Haiti', 43, 4)
(' Haiti', 44, 4)
(' Haiti', 45, 2)
(' Haiti', 48, 2)
(' Haiti', 51, 4)
(' Haiti', 52, 2)
(' Haiti', 53, 4)
(' Haiti', 54, 6)
(' Haiti', 56, 2)
(' Haiti', 58, 2)
(' Haiti', 63, 2)
(' Guatemala', 19, 6)
(' Guatemala', 20, 6)
(' Guatemala', 21, 4)
(' Guatemala', 22, 6)
(' Guatemala', 23, 8)
(' Guatemala', 24, 2)
(' Guatemala', 25, 12)
(' Guatemala', 26, 4)
(' Guatemala', 27, 12)
(' Guatemala', 28, 4)
(' Guatemala', 29, 6)
(' Guatemala', 30, 4)
(' Guatemala', 32, 2)
(' Guatemala', 33, 4)
(' Guatemala', 34, 6)
(' Guatemala', 35, 2)
(' Guatemala', 36, 2)
(' Guatemala', 37, 4)
(' Guatemala', 38, 2)
(' Guatemala', 40, 2)
(' Guatemala', 41, 8)
(' Guatemala', 45, 2)
(' Guatemala', 46, 8)
(' Guatemala', 53, 2)
(' Guatemala', 54, 2)
(' Guatemala', 58, 2)
(' Guatemala', 59, 2)
(' Guatemala', 61, 2)
(' Guatemala', 66, 2)
(' Greece', 22, 4)
(' Greece', 23, 2)
(' Greece', 24, 2)
(' Greece', 27, 2)
(' Greece', 32, 4)
(' Greece', 40, 2)
(' Greece', 43, 2)
(' Greece', 44, 2)
(' Greece', 46, 2)
(' Greece', 48, 2)
(' Greece', 49, 6)
(' Greece', 51, 2)
(' Greece', 52, 2)
(' Greece', 53, 6)
(' Greece', 54, 2)
(' Greece', 55, 2)
(' Greece', 56, 2)
(' Greece', 58, 6)
(' Greece', 59, 2)
(' Greece', 65, 4)
(' Germany', 18, 2)
(' Germany', 20, 10)
(' Germany', 21, 6)
(' Germany', 22, 8)
(' Germany', 23, 2)
(' Germany', 24, 4)
(' Germany', 26, 6)
(' Germany', 27, 6)
(' Germany', 28, 10)
(' Germany', 29, 16)
(' Germany', 30, 16)
(' Germany', 31, 8)
(' Germany', 32, 6)
(' Germany', 33, 10)
(' Germany', 34, 16)
(' Germany', 35, 10)
(' Germany', 36, 8)
(' Germany', 37, 4)
(' Germany', 38, 2)
(' Germany', 39, 6)
(' Germany', 40, 2)
(' Germany', 41, 4)
(' Germany', 42, 2)
(' Germany', 43, 8)
(' Germany', 44, 2)
(' Germany', 45, 10)
(' Germany', 46, 12)
(' Germany', 47, 10)
(' Germany', 48, 6)
(' Germany', 49, 2)
(' Germany', 50, 4)
(' Germany', 51, 4)
(' Germany', 52, 6)
(' Germany', 53, 4)
(' Germany', 54, 4)
(' Germany', 55, 4)
(' Germany', 56, 2)
(' Germany', 57, 4)
(' Germany', 58, 2)
(' Germany', 59, 2)
(' Germany', 60, 4)
(' Germany', 61, 2)
(' Germany', 62, 4)
(' Germany', 65, 2)
(' Germany', 66, 2)
(' Germany', 67, 4)
(' Germany', 69, 2)
(' Germany', 71, 2)
(' Germany', 74, 2)
(' France', 20, 2)
(' France', 24, 2)
(' France', 27, 2)
(' France', 28, 4)
(' France', 29, 4)
(' France', 30, 2)
(' France', 31, 2)
(' France', 32, 2)
(' France', 33, 4)
(' France', 34, 6)
(' France', 37, 4)
(' France', 39, 2)
(' France', 42, 2)
(' France', 43, 2)
(' France', 45, 2)
(' France', 47, 2)
(' France', 49, 2)
(' France', 51, 2)
(' France', 53, 2)
(' France', 55, 2)
(' France', 58, 2)
(' France', 64, 4)
(' England', 17, 2)
(' England', 19, 4)
(' England', 20, 2)
(' England', 21, 2)
(' England', 22, 2)
(' England', 23, 4)
(' England', 24, 6)
(' England', 25, 2)
(' England', 26, 2)
(' England', 27, 2)
(' England', 28, 6)
(' England', 29, 4)
(' England', 30, 8)
(' England', 31, 4)
(' England', 32, 6)
(' England', 33, 6)
(' England', 34, 10)
(' England', 36, 4)
(' England', 37, 4)
(' England', 38, 4)
(' England', 39, 4)
(' England', 40, 6)
(' England', 41, 4)
(' England', 42, 4)
(' England', 43, 4)
(' England', 44, 8)
(' England', 45, 8)
(' England', 46, 4)
(' England', 47, 2)
(' England', 48, 6)
(' England', 49, 2)
(' England', 50, 2)
(' England', 51, 2)
(' England', 52, 2)
(' England', 54, 4)
(' England', 55, 6)
(' England', 57, 2)
(' England', 59, 8)
(' England', 60, 2)
(' England', 61, 2)
(' England', 65, 2)
(' England', 66, 2)
(' England', 67, 2)
(' England', 68, 2)
(' England', 72, 2)
(' England', 73, 2)
(' England', 90, 2)
(' El-Salvador', 17, 4)
(' El-Salvador', 19, 8)
(' El-Salvador', 20, 10)
(' El-Salvador', 21, 4)
(' El-Salvador', 22, 4)
(' El-Salvador', 23, 12)
(' El-Salvador', 24, 14)
(' El-Salvador', 25, 16)
(' El-Salvador', 26, 6)
(' El-Salvador', 27, 6)
(' El-Salvador', 28, 6)
(' El-Salvador', 29, 8)
(' El-Salvador', 30, 2)
(' El-Salvador', 31, 4)
(' El-Salvador', 32, 2)
(' El-Salvador', 33, 12)
(' El-Salvador', 34, 6)
(' El-Salvador', 36, 6)
(' El-Salvador', 37, 10)
(' El-Salvador', 38, 2)
(' El-Salvador', 39, 4)
(' El-Salvador', 40, 4)
(' El-Salvador', 41, 4)
(' El-Salvador', 42, 10)
(' El-Salvador', 44, 2)
(' El-Salvador', 45, 2)
(' El-Salvador', 46, 2)
(' El-Salvador', 47, 8)
(' El-Salvador', 48, 4)
(' El-Salvador', 50, 6)
(' El-Salvador', 51, 4)
(' El-Salvador', 52, 8)
(' El-Salvador', 53, 2)
(' El-Salvador', 58, 2)
(' El-Salvador', 59, 2)
(' El-Salvador', 61, 2)
(' El-Salvador', 63, 2)
(' El-Salvador', 79, 2)
(' Ecuador', 21, 2)
(' Ecuador', 23, 2)
(' Ecuador', 24, 4)
(' Ecuador', 25, 2)
(' Ecuador', 27, 2)
(' Ecuador', 28, 4)
(' Ecuador', 29, 8)
(' Ecuador', 30, 2)
(' Ecuador', 32, 4)
(' Ecuador', 33, 2)
(' Ecuador', 35, 2)
(' Ecuador', 36, 2)
(' Ecuador', 37, 2)
(' Ecuador', 42, 4)
(' Ecuador', 44, 2)
(' Ecuador', 46, 4)
(' Ecuador', 48, 2)
(' Ecuador', 50, 2)
(' Ecuador', 67, 2)
(' Ecuador', 90, 2)
(' Dominican-Republic', 18, 2)
(' Dominican-Republic', 21, 6)
(' Dominican-Republic', 22, 6)
(' Dominican-Republic', 23, 8)
(' Dominican-Republic', 24, 6)
(' Dominican-Republic', 25, 4)
(' Dominican-Republic', 26, 6)
(' Dominican-Republic', 27, 8)
(' Dominican-Republic', 28, 4)
(' Dominican-Republic', 29, 6)
(' Dominican-Republic', 30, 2)
(' Dominican-Republic', 32, 2)
(' Dominican-Republic', 34, 4)
(' Dominican-Republic', 35, 2)
(' Dominican-Republic', 38, 2)
(' Dominican-Republic', 39, 8)
(' Dominican-Republic', 40, 6)
(' Dominican-Republic', 41, 4)
(' Dominican-Republic', 42, 2)
(' Dominican-Republic', 43, 2)
(' Dominican-Republic', 44, 6)
(' Dominican-Republic', 45, 2)
(' Dominican-Republic', 46, 4)
(' Dominican-Republic', 47, 2)
(' Dominican-Republic', 48, 6)
(' Dominican-Republic', 50, 4)
(' Dominican-Republic', 51, 2)
(' Dominican-Republic', 52, 2)
(' Dominican-Republic', 53, 8)
(' Dominican-Republic', 56, 2)
(' Dominican-Republic', 57, 2)
(' Dominican-Republic', 58, 2)
(' Dominican-Republic', 59, 2)
(' Dominican-Republic', 60, 2)
(' Dominican-Republic', 62, 2)
(' Dominican-Republic', 78, 2)
(' Cuba', 21, 4)
(' Cuba', 23, 6)
(' Cuba', 25, 2)
(' Cuba', 27, 2)
(' Cuba', 28, 6)
(' Cuba', 29, 2)
(' Cuba', 30, 2)
(' Cuba', 31, 6)
(' Cuba', 32, 2)
(' Cuba', 33, 8)
(' Cuba', 34, 2)
(' Cuba', 35, 2)
(' Cuba', 36, 2)
(' Cuba', 37, 10)
(' Cuba', 38, 8)
(' Cuba', 39, 6)
(' Cuba', 40, 6)
(' Cuba', 41, 6)
(' Cuba', 42, 2)
(' Cuba', 43, 4)
(' Cuba', 44, 4)
(' Cuba', 45, 2)
(' Cuba', 46, 4)
(' Cuba', 47, 12)
(' Cuba', 48, 2)
(' Cuba', 49, 2)
(' Cuba', 50, 4)
(' Cuba', 51, 2)
(' Cuba', 52, 12)
(' Cuba', 53, 6)
(' Cuba', 54, 4)
(' Cuba', 55, 2)
(' Cuba', 56, 4)
(' Cuba', 57, 8)
(' Cuba', 58, 2)
(' Cuba', 59, 4)
(' Cuba', 60, 2)
(' Cuba', 62, 2)
(' Cuba', 63, 4)
(' Cuba', 64, 4)
(' Cuba', 66, 2)
(' Cuba', 67, 2)
(' Cuba', 68, 2)
(' Cuba', 70, 2)
(' Cuba', 72, 4)
(' Cuba', 77, 2)
(' Cuba', 82, 2)
(' Columbia', 18, 2)
(' Columbia', 21, 6)
(' Columbia', 23, 4)
(' Columbia', 25, 8)
(' Columbia', 26, 6)
(' Columbia', 28, 4)
(' Columbia', 29, 6)
(' Columbia', 31, 4)
(' Columbia', 32, 6)
(' Columbia', 33, 4)
(' Columbia', 34, 4)
(' Columbia', 36, 4)
(' Columbia', 38, 4)
(' Columbia', 39, 4)
(' Columbia', 41, 2)
(' Columbia', 43, 2)
(' Columbia', 45, 4)
(' Columbia', 46, 2)
(' Columbia', 48, 2)
(' Columbia', 49, 12)
(' Columbia', 50, 2)
(' Columbia', 51, 2)
(' Columbia', 52, 2)
(' Columbia', 53, 2)
(' Columbia', 54, 2)
(' Columbia', 56, 2)
(' Columbia', 57, 4)
(' Columbia', 60, 4)
(' Columbia', 62, 2)
(' Columbia', 64, 4)
(' Columbia', 75, 2)
(' China', 22, 2)
(' China', 23, 4)
(' China', 24, 4)
(' China', 25, 2)
(' China', 27, 2)
(' China', 28, 2)
(' China', 29, 2)
(' China', 30, 8)
(' China', 31, 4)
(' China', 32, 4)
(' China', 33, 8)
(' China', 34, 8)
(' China', 35, 4)
(' China', 36, 6)
(' China', 37, 2)
(' China', 39, 4)
(' China', 40, 8)
(' China', 41, 6)
(' China', 43, 4)
(' China', 44, 2)
(' China', 45, 10)
(' China', 46, 4)
(' China', 48, 6)
(' China', 49, 2)
(' China', 50, 2)
(' China', 51, 2)
(' China', 52, 4)
(' China', 53, 4)
(' China', 54, 4)
(' China', 56, 4)
(' China', 57, 2)
(' China', 59, 2)
(' China', 60, 2)
(' China', 61, 2)
(' China', 62, 2)
(' China', 63, 2)
(' China', 64, 4)
(' China', 69, 2)
(' China', 70, 2)
(' China', 75, 2)
(' Canada', 17, 4)
(' Canada', 18, 2)
(' Canada', 19, 2)
(' Canada', 20, 4)
(' Canada', 22, 2)
(' Canada', 23, 6)
(' Canada', 24, 6)
(' Canada', 25, 10)
(' Canada', 26, 4)
(' Canada', 27, 4)
(' Canada', 28, 6)
(' Canada', 29, 8)
(' Canada', 30, 6)
(' Canada', 31, 4)
(' Canada', 32, 6)
(' Canada', 33, 8)
(' Canada', 34, 2)
(' Canada', 35, 2)
(' Canada', 36, 8)
(' Canada', 37, 8)
(' Canada', 38, 8)
(' Canada', 39, 2)
(' Canada', 40, 8)
(' Canada', 41, 6)
(' Canada', 42, 2)
(' Canada', 43, 2)
(' Canada', 44, 4)
(' Canada', 45, 12)
(' Canada', 46, 4)
(' Canada', 47, 4)
(' Canada', 48, 2)
(' Canada', 49, 4)
(' Canada', 50, 6)
(' Canada', 51, 8)
(' Canada', 52, 6)
(' Canada', 53, 8)

(' Canada', 54, 2)
(' Canada', 55, 2)
(' Canada', 56, 8)
(' Canada', 57, 2)
(' Canada', 58, 4)
(' Canada', 61, 2)
(' Canada', 62, 6)
(' Canada', 64, 4)
(' Canada', 65, 2)
(' Canada', 66, 2)
(' Canada', 67, 4)
(' Canada', 68, 2)
(' Canada', 71, 2)
(' Canada', 72, 4)
(' Canada', 73, 4)
(' Canada', 76, 2)
(' Canada', 80, 2)
(' Cambodia', 18, 2)
(' Cambodia', 25, 2)
(' Cambodia', 27, 4)
(' Cambodia', 28, 2)
(' Cambodia', 32, 2)
(' Cambodia', 34, 2)
(' Cambodia', 35, 2)
(' Cambodia', 36, 2)
(' Cambodia', 37, 4)
(' Cambodia', 40, 4)
(' Cambodia', 42, 2)
(' Cambodia', 46, 2)
(' Cambodia', 48, 2)
(' Cambodia', 50, 2)
(' Cambodia', 51, 2)
(' Cambodia', 65, 2)
(' ?', 17, 4)
(' ?', 18, 16)
(' ?', 19, 10)
(' ?', 20, 20)
(' ?', 21, 22)
(' ?', 22, 24)
(' ?', 23, 12)
(' ?', 24, 28)
(' ?', 25, 22)
(' ?', 26, 36)
(' ?', 27, 30)
(' ?', 28, 38)
(' ?', 29, 24)
(' ?', 30, 38)
(' ?', 31, 36)
(' ?', 32, 34)
(' ?', 33, 26)
(' ?', 34, 48)
(' ?', 35, 36)
(' ?', 36, 46)
(' ?', 37, 44)
(' ?', 38, 40)
(' ?', 39, 38)
(' ?', 40, 24)
(' ?', 41, 44)
(' ?', 42, 48)
(' ?', 43, 28)
(' ?', 44, 20)
(' ?', 45, 34)
(' ?', 46, 30)
(' ?', 47, 24)
(' ?', 48, 10)
(' ?', 49, 8)
(' ?', 50, 26)
(' ?', 51, 14)
(' ?', 52, 18)
(' ?', 53, 8)
(' ?', 54, 10)
(' ?', 55, 24)
(' ?', 56, 20)
(' ?', 57, 10)
(' ?', 58, 4)
(' ?', 59, 6)
(' ?', 60, 10)
(' ?', 61, 10)
(' ?', 62, 6)
(' ?', 63, 10)
(' ?', 64, 10)
(' ?', 65, 6)
(' ?', 66, 6)
(' ?', 67, 2)
(' ?', 68, 6)
(' ?', 69, 2)
(' ?', 70, 2)
(' ?', 72, 4)
(' ?', 74, 2)
(' ?', 76, 2)
(' ?', 81, 4)
(' ?', 90, 2)

7. Compute a new column as 'Net-Capital-Gain' from the two columns 'capital-gain' and
'capital-loss'

In [31]:
str='''alter table sqladb add column "Net-Capital-Gain" "float"'''
results=con.execute(str)
con.commit()

In [33]:
str1='''update sqladb set "Net-Capital-Gain"="capital-gain"-"capital-loss"'''
con.execute(str1)
con.commit()

In [35]:
str='''select * from sqladb limit 5'''
for rec in con.execute(str):
    print(rec)

(39, ' State-gov', 77516, ' Bachelors', 13, ' Never-married', ' Adm-clerical', ' Not-in-family', ' White', ' Male', 2174, 0, 40, ' United-States', ' <=50K', 2174.0)
(50, ' Self-emp-not-inc', 83311, ' Bachelors', 13, ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White', ' Male', 0, 0, 13, ' United-States', ' <=50K', 0.0)
(38, ' Private', 215646, ' HS-grad', 9, ' Divorced', ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K', 0.0)
(53, ' Private', 234721, ' 11th', 7, ' Married-civ-spouse', ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40, ' United-States', ' <=50K', 0.0)
(28, ' Private', 338409, ' Bachelors', 13, ' Married-civ-spouse', ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40, ' Cuba', ' <=50K', 0.0)